add_rules("mode.debug", "mode.release")
add_requires("gtest")

target("float")
    set_kind("static")
    add_includedirs("include/float", {public = true})
    add_defines("FLOAT_64")
    add_files("src/float/*.cpp")

target("test_float")
    set_kind("binary")
    set_group("tests")
    add_files("test/test_float.cpp")
    add_deps("float")
    add_defines("FLOAT_64")
    add_packages("gtest")

target("complex")
    set_kind("static")
    add_includedirs("include/complex", {public = true})
    add_deps("float")
    add_defines("FLOAT_64")
    add_files("src/complex/*.cpp")

target("test_complex")
    set_kind("binary")
    set_group("tests")
    add_files("test/test_complex.cpp")
    add_deps("complex")
    add_defines("FLOAT_64")
    add_packages("gtest")

target("fft")
    set_kind("static")
    add_includedirs("include/fft", {public = true})
    add_deps("float")
    add_defines("FLOAT_64")
    add_deps("complex")
    add_files("src/fft/*.cpp")
    